version: "2.1"
services:
  server:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "80:80"
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - postgres.env
    volumes:
      - /var/lib/postgresql
    ports:
      - "5432:5432"
